2021-05-03 02:23:32,323 INFO    MainThread:72 [wandb_setup.py:_flush():69] setting env: {}
2021-05-03 02:23:32,324 INFO    MainThread:72 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-03 02:23:32,324 INFO    MainThread:72 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '8d3153ad3bb912131270614820cf8ed59c9d94d4'}
2021-05-03 02:23:32,325 INFO    MainThread:72 [wandb_init.py:_log_setup():336] Logging user logs to /content/drive/MyDrive/Trash/code/wandb/run-20210503_022332-3c2600hw/logs/debug.log
2021-05-03 02:23:32,326 INFO    MainThread:72 [wandb_init.py:_log_setup():337] Logging internal logs to /content/drive/MyDrive/Trash/code/wandb/run-20210503_022332-3c2600hw/logs/debug-internal.log
2021-05-03 02:23:32,327 INFO    MainThread:72 [wandb_init.py:init():369] calling init triggers
2021-05-03 02:23:32,327 INFO    MainThread:72 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-03 02:23:32,327 INFO    MainThread:72 [wandb_init.py:init():391] re-initializing run, found existing run on stack: nv7xdlv6
2021-05-03 02:23:32,329 INFO    MainThread:72 [wandb_run.py:finish():1197] finishing run pstage12/chanyub/nv7xdlv6
2021-05-03 02:23:32,383 INFO    MainThread:72 [jupyter.py:save_history():320] not saving jupyter history
2021-05-03 02:23:32,383 INFO    MainThread:72 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-03 02:23:32,383 INFO    MainThread:72 [wandb_init.py:_jupyter_teardown():268] cleaning up jupyter logic
2021-05-03 02:23:32,384 INFO    MainThread:72 [wandb_run.py:_atexit_cleanup():1524] got exitcode: 0
2021-05-03 02:23:32,385 INFO    MainThread:72 [wandb_run.py:_restore():1496] restore
2021-05-03 02:24:30,190 INFO    MainThread:72 [wandb_init.py:init():418] starting backend
2021-05-03 02:24:30,190 INFO    MainThread:72 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-03 02:24:30,199 INFO    MainThread:72 [backend.py:ensure_launched():123] starting backend process...
2021-05-03 02:24:30,261 INFO    MainThread:72 [backend.py:ensure_launched():128] started backend process with pid: 915
2021-05-03 02:24:30,265 INFO    MainThread:72 [wandb_init.py:init():423] backend started and connected
2021-05-03 02:24:30,292 INFO    MainThread:72 [wandb_init.py:init():465] updated telemetry
2021-05-03 02:24:30,295 INFO    MainThread:72 [wandb_init.py:init():484] communicating current version
2021-05-03 02:24:31,184 INFO    MainThread:72 [wandb_init.py:init():489] got version response 
2021-05-03 02:24:31,184 INFO    MainThread:72 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-03 02:24:31,290 INFO    MainThread:72 [wandb_init.py:init():522] starting run threads in backend
2021-05-03 02:24:33,041 INFO    MainThread:72 [wandb_run.py:_console_start():1554] atexit reg
2021-05-03 02:24:33,045 INFO    MainThread:72 [wandb_run.py:_redirect():1401] redirect: SettingsConsole.WRAP
2021-05-03 02:24:33,047 INFO    MainThread:72 [wandb_run.py:_redirect():1444] Wrapping output streams.
2021-05-03 02:24:33,048 INFO    MainThread:72 [wandb_run.py:_redirect():1468] Redirects installed.
2021-05-03 02:24:33,048 INFO    MainThread:72 [wandb_init.py:init():546] run started, returning control to user process
2021-05-03 02:24:33,048 INFO    MainThread:72 [wandb_config.py:__setitem__():141] config set learning_rate = 0.01 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f093ed4c650>>
2021-05-03 02:24:33,049 INFO    MainThread:72 [wandb_run.py:_config_callback():779] config_cb learning_rate 0.01 None
